CREATE TABLE SERVDESK.CLASSIFICACAO(
    ID_CLASSIFICACAO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

CREATE SEQUENCE  SERVDESK.SEQ_CLASSIFICACAO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER SERVDESK.TGR_CLASSIFICACAO_INS 
BEFORE INSERT ON SERVDESK.CLASSIFICACAO
FOR EACH ROW
  WHEN (NEW.ID_CLASSIFICACAO IS NULL) BEGIN
  SELECT SERVDESK.SEQ_CLASSIFICACAO.NEXTVAL
  INTO   :NEW.ID_CLASSIFICACAO
  FROM   DUAL;
END;
/
