CREATE TABLE SERVDESK.CLASSIFICACAO_CONTABIL(
    ID_CLASSIFICACAO_CONTABIL INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(200),
    ID_EMPRESA NUMBER(3) NOT NULL, 
    STATUS CHAR(1) NOT NULL,
    MESANO_INICIO DATE NOT NULL,
    MESANO_FIM DATE NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

CREATE SEQUENCE  SERVDESK.SEQ_CLASSIFICACAO_CONTABIL  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER SERVDESK.TGR_CLASSIFICACAO_CONTABIL_INS 
BEFORE INSERT ON SERVDESK.CLASSIFICACAO_CONTABIL
FOR EACH ROW
  WHEN (NEW.ID_CLASSIFICACAO_CONTABIL IS NULL) BEGIN
  SELECT SERVDESK.SEQ_CLASSIFICACAO_CONTABIL.NEXTVAL
  INTO   :NEW.ID_CLASSIFICACAO_CONTABIL
  FROM   DUAL;
END;
/
