CREATE TABLE SERVDESK.CLASSIFICACAO_ESG(
    ID_CLASSIFICACAO_ESG INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

CREATE SEQUENCE  SERVDESK.SEQ_CLASSIFICACAO_ESG  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER SERVDESK.TGR_CLASSIFICACAO_ESG_INS 
BEFORE INSERT ON SERVDESK.CLASSIFICACAO_ESG
FOR EACH ROW
  WHEN (NEW.ID_CLASSIFICACAO_ESG IS NULL) BEGIN
  SELECT SERVDESK.SEQ_CLASSIFICACAO_ESG.NEXTVAL
  INTO   :NEW.ID_CLASSIFICACAO_ESG
  FROM   DUAL;
END;
/
