CREATE TABLE SERVDESK.CENARIO_CLASSIF_CONTABIL(
    ID_CENARIO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

CREATE SEQUENCE  SERVDESK.SEQ_CENARIO_CLASSIF_CONTABIL  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER SERVDESK.TGR_CENARIO_CLASSIF_CONT_INS 
BEFORE INSERT ON SERVDESK.CENARIO_CLASSIF_CONTABIL
FOR EACH ROW
  WHEN (NEW.ID_CENARIO IS NULL) BEGIN
  SELECT SERVDESK.SEQ_CENARIO_CLASSIF_CONTABIL.NEXTVAL
  INTO   :NEW.ID_CENARIO
  FROM   DUAL;
END;
/