CREATE TABLE SERVDESK.PARAMETRIZACAO_CENARIO (
    ID_PARAMETRIZACAO_CENARIO INT NOT NULL PRIMARY KEY,
    ID_CLASSIFICACAO_CONTABIL INT NOT NULL,
    ID_CLASSIFICACAO_ESG INT NOT NULL,
    ID_CENARIO_CLASSIF_CONTABIL INT NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

ALTER TABLE SERVDESK.PARAMETRIZACAO_CENARIO ADD CONSTRAINT FK_CLASSIF_ESG FOREIGN KEY (ID_CLASSIFICACAO_ESG) REFERENCES CLASSIFICACAO_ESG(ID_CLASSIFICACAO_ESG);
ALTER TABLE SERVDESK.PARAMETRIZACAO_CENARIO ADD CONSTRAINT FK_CENARIO FOREIGN KEY (ID_CENARIO_CLASSIF_CONTABIL) REFERENCES CENARIO_CLASSIF_CONTABIL(ID_CENARIO_CLASSIF_CONTABIL);
CREATE SEQUENCE  SERVDESK.SEQ_PARAMETRIZACAO_CENARIO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER SERVDESK.TGR_PARAMETRIZACAO_CENARIO_INS 
BEFORE INSERT ON SERVDESK.PARAMETRIZACAO_CENARIO
FOR EACH ROW
  WHEN (NEW.ID_PARAMETRIZACAO_CENARIO IS NULL) BEGIN
  SELECT SERVDESK.SEQ_PARAMETRIZACAO_CENARIO.NEXTVAL
  INTO   :NEW.ID_PARAMETRIZACAO_CENARIO
  FROM   DUAL;
END;
/