CREATE TABLE SERVDESK.PARAMETRIZACAO_CLASSIF_GERAL (
    ID_PARAMETRIZACAO_CLASSIF_GERAL INT NOT NULL PRIMARY KEY,
    ID_GRUPO_PROGRAMA INT NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

ALTER TABLE SERVDESK.PARAMETRIZACAO_CLASSIF_GERAL ADD CONSTRAINT FK_GRUPO_PROGRAMA FOREIGN KEY (ID_GRUPO_PROGRAMA) REFERENCES CENARIO(ID_GRUPO_PROGRAMA);
CREATE INDEX SERVDESK.IDX_PARAMETRIZACAO_CLASSIF_GERAL ON PARAMETRIZACAO_CLASSIF_GERAL (ID_PARAMETRIZACAO_CLASSIF_GERAL);

CREATE SEQUENCE  SERVDESK.SEQ_PARAMETRIZACAO_CLASSIF_GERAL  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER SERVDESK.TGR_PARAMETRIZACAO_CLASSIF_GERAL_INS 
BEFORE INSERT ON SERVDESK.PARAMETRIZACAO_CLASSIF_GERAL
FOR EACH ROW
  WHEN (NEW.ID_LANCAMENTO IS NULL) BEGIN
  SELECT SERVDESK.SEQ_PARAMETRIZACAO_CLASSIF_GERAL.NEXTVAL
  INTO   :NEW.ID_LANCAMENTO
  FROM   DUAL;
END;
/