CREATE TABLE SERVDESK.PARAMETRIZACAO_ESG_GERAL (
    ID_PARAM_ESG_GERAL INT NOT NULL PRIMARY KEY,
    ID_CLASSIFICACAO_ESG INT NOT NULL,
    ID_GRUPO_PROGRAMA INT NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

CREATE SEQUENCE  SERVDESK.SEQ_PARAM_ESG_GERAL  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE SERVDESK.PARAMETRIZACAO_ESG_GERAL ADD CONSTRAINT FK_CLASSIF_ESG_GERAL  FOREIGN KEY (ID_CLASSIFICACAO_ESG) REFERENCES CLASSIFICACAO_ESG(ID_CLASSIFICACAO_ESG);

CREATE OR REPLACE TRIGGER SERVDESK.TGR_PARAM_ESG_GERAL_INS 
BEFORE INSERT ON SERVDESK.PARAMETRIZACAO_ESG_GERAL
FOR EACH ROW
  WHEN (NEW.ID_PARAM_ESG_GERAL IS NULL) BEGIN
  SELECT SERVDESK.SEQ_PARAM_ESG_GERAL.NEXTVAL
  INTO   :NEW.ID_PARAM_ESG_GERAL
  FROM   DUAL;
END;
/