CREATE TABLE SERVDESK.PARAMETRIZACAO_ESG_EXC (
    ID_PARAM_ESG_EXC INT NOT NULL PRIMARY KEY, 
    ID_CENARIO_CLASSIF_CONTABIL INT NOT NULL,
    ID_EMPRESA NUMBER(3) NOT NULL, 
    ID_GRUPO_PROGRAMA NUMBER(4) NOT NULL, 
    ID_PROGRAMA NUMBER(4) NOT NULL, 
    ID_PROJETO NUMBER(5) NOT NULL,
    ID_CLASSIFICACAO_ESG INT NOT NULL,
    DTCRIACAO DATE DEFAULT SYSDATE,
    USCRIACAO VARCHAR2(60),
    DTALTERACAO DATE,
    USALTERACAO VARCHAR2(60)
);

ALTER TABLE SERVDESK.PARAMETRIZACAO_ESG_EXC ADD CONSTRAINT FK_PARAM_CLASSIF_ESG FOREIGN KEY (ID_CLASSIFICACAO_ESG) REFERENCES CLASSIFICACAO_ESG(ID_CLASSIFICACAO_ESG);
ALTER TABLE SERVDESK.PARAMETRIZACAO_ESG_EXC ADD CONSTRAINT FK_PARAM_CENARIO FOREIGN KEY (ID_CENARIO_CLASSIF_CONTABIL) REFERENCES CENARIO_CLASSIF_CONTABIL(ID_CENARIO_CLASSIF_CONTABIL);

CREATE SEQUENCE  SERVDESK.SEQ_PARAM_ESG_EXC  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER SERVDESK.TGR_PARAM_ESG_EXC_INS 
BEFORE INSERT ON SERVDESK.PARAMETRIZACAO_ESG_EXC
FOR EACH ROW
  WHEN (NEW.ID_PARAM_ESG_EXC IS NULL) BEGIN
  SELECT SERVDESK.SEQ_PARAM_ESG_EXC.NEXTVAL
  INTO   :NEW.ID_PARAM_ESG_EXC
  FROM   DUAL;
END;
/