
CREATE TABLE LANC_CLASSIF_CONTABIL  (
    ID_LANCAMENTO INT NOT NULL PRIMARY KEY,
    ID_IMPORTACAO VARCHAR2(17) NOT NULL,
    ID_TIPO_CLASSIF VARCHAR2(50) NOT NULL,
    EMPCOD INT NOT NULL,
    DT_LANCAMENTO_SAP DATE,    
    PRJCOD INT NOT NULL,    
    PEP VARCHAR2(40) NOT NULL,    
    DESCRICAO_PEP VARCHAR2(200),
    CONTA_CONTABIL VARCHAR2(15),    
    VALOR NUMBER(18,2),
    CLASSE_IMOBILIZADO VARCHAR2(10),
    CHAVE_DEPRECIACAO VARCHAR2(4),
    ANO_EXERCICIO VARCHAR2(4),
    IMOBILIZADO VARCHAR2(12),
    SUB_NUMERO_IMOB VARCHAR2(4),
    NOMENCLATURA VARCHAR2(40)
);
 
CREATE SEQUENCE  SERVDESK.LANC_CONTABIL  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
 
CREATE OR REPLACE TRIGGER SERVDESK.TGR_LANC_CONTABIL_INS 
BEFORE INSERT ON SERVDESK.LANC_CLASSIF_CONTABIL
FOR EACH ROW
  WHEN (NEW.ID_LANCAMENTO IS NULL) BEGIN
  SELECT SERVDESK.LANC_CONTABIL.NEXTVAL
  INTO   :NEW.ID_LANCAMENTO
  FROM   DUAL;
END;
/