DELETE SERVDESK.CLASSIFICACAO_ESG;
DELETE SERVDESK.CENARIO_CLASSIF_CONTABIL;
DELETE SERVDESK.CLASSIFICACAO_CONTABIL;
DELETE SERVDESK.PARAMETRIZACAO_CENARIO;
DELETE SERVDESK.PARAMETRIZACAO_ESG_EXC;
DELETE SERVDESK.PARAMETRIZACAO_ESG_GERAL;
DROP TABLE SERVDESK.PARAMETRIZACAO_CENARIO;
DROP SEQUENCE SERVDESK.SEQ_PARAMETRIZACAO_CENARIO;
DROP TABLE SERVDESK.PARAMETRIZACAO_ESG_EXC;
DROP SEQUENCE SERVDESK.SEQ_PARAM_ESG_EXC;
DROP TABLE SERVDESK.PARAMETRIZACAO_ESG_GERAL;
DROP SEQUENCE SERVDESK.SEQ_PARAM_ESG_GERAL;
DROP TABLE SERVDESK.CLASSIFICACAO_CONTABIL;
DROP SEQUENCE SERVDESK.SEQ_CLASSIFICACAO_CONTABIL;
DROP TABLE SERVDESK.CLASSIFICACAO_ESG;
DROP SEQUENCE SERVDESK.SEQ_CLASSIFICACAO_ESG;
DROP TABLE SERVDESK.CENARIO_CLASSIF_CONTABIL;
DROP SEQUENCE SERVDESK.SEQ_CENARIO_CLASSIF_CONTABIL;


